import * as yup from 'yup';

export const validateSchema = yup.object().shape({
  id: yup.string().min(9, "ID should be 9 digit").max(9, "ID should be 9 digit").required("You must enter your organization ID"),
  clientName: yup.string().required("You must enter your Client name"),
  // organizationType: yup.string().required("You must select your organization type"),
  //parentClientName : yup.string().required("You must enter your parent client name"),
  fullName: yup.string().required("You must enter your name"),
  primaryPhoneNumber: yup.string().required("You must enter your primary phone number"),
  designation: yup.string(),
  email: yup.string().required('You must enter your email').email('Please enter a valid email'),
  password: yup.string().required('You must enter your password'),

  contactEndDate: yup.string().required('You must enter your contact end date').typeError("Please Enter Valid Date"),
  commision: yup.string().required('You must enter your commision'),
  smsCost: yup.string().required('You must enter your sms cost'),
  emailCost: yup.string().required('You must enter your email cost'),
  creditCheckCost: yup.string().required('You must enter your credit check cost'),
  ehfCost: yup.string().required('You must enter your ehf cost'),

  contactEndDatep2: yup.string().required('You must enter your contact end date'),
  commisionp2: yup.string().required('You must enter your commision'),
  smsCostp2: yup.string().required('You must enter your sms cost'),
  emailCostp2: yup.string().required('You must enter your email cost'),
  creditCheckCostp2: yup.string().required('You must enter your credit check cost'),
  ehfCostp2: yup.string().required('You must enter your ehf cost'),

  contactEndDatep3: yup.string().required('You must enter your contact end date'),
  commisionp3: yup.string().required('You must enter your commision'),
  smsCostp3: yup.string().required('You must enter your sms cost'),
  emailCostp3: yup.string().required('You must enter your email cost'),
  creditCheckCostp3: yup.string().required('You must enter your credit check cost'),
  ehfCostp3: yup.string().required('You must enter your ehf cost'),

  billingPhoneNumber: yup.string().required('You must enter your billing phone number'),
  billingEmail: yup.string().required('You must enter your billing email'),
  billingAddress: yup.string().required('You must enter your billing address'),
  zip: yup.string().required('You must enter your zip'),
  city: yup.string().required('You must enter your city'),
  country: yup.string().required('You must enter your country'),
  // shippingPhoneNumber: yup.string().required('You must enter your shipping phone number'),
  // shippingEmail: yup.string().required('You must enter your shipping email'),
  // shippingAddress: yup.string().required('You must enter your shipping address'),
  // shippingZip: yup.string().required('You must enter your shipping zip'),
  // shippingCity: yup.string().required('You must enter your shipping city'),
  // shippingCountry: yup.string().required('You must enter your shipping country'),
  bankName: yup.string().required('You must enter your bank name'),
  accountNumber: yup.string()
    .required('You must enter your account number')
    .matches(/^(\S+$)/g, 'This field cannot contain blankspaces'),
  IBAN: yup.string().required('You must enter your IBAN'),
  SWIFTCode: yup.string().required('You must enter your SWIFT code'),

  APTICuserName: yup.string().required('You must enter your APTIC user name'),
  APTICpassword: yup.string().required('You must enter your APTIC password'),
  fpReference: yup.string().required('You must enter your fp reference'),
  name: yup.string().required('You must enter your name'),
  creditLimitCustomer: yup.string().required('You must enter your credit limit for customer'),
  APTIEngineCuserName: yup.string().required('You must enter username'),
  APTIEnginePassword: yup.string().required('You must enter password'),
  fakturaB2B: yup.string().required('You must enter Faktura B2B'),
  fakturaB2C: yup.string().required('You must enter Faktura B2C'),
});

export const validateSchemaOnBoard = yup.object().shape({
  id: yup.string().min(9, "ID should be 9 digit").max(9, "ID should be 9 digit").required("You must enter your organization ID"),
  clientName: yup.string().required("You must enter your Client name"),
  // organizationType: yup.string().required("You must select your organization type"),
  //parentClientName : yup.string().required("You must enter your parent client name"),
  fullName: yup.string().required("You must enter your name"),
  primaryPhoneNumber: yup.string().required("You must enter your primary phone number"),
  designation: yup.string(),
  email: yup.string().required('You must enter your email').email('Please enter a valid email'),
  // password: yup.string().required('You must enter your password'),

  contactEndDate: yup.string().required('You must enter your contact end date') .typeError('You must enter your contact end date'),
  commision: yup.string().required('You must enter your commision'),
  smsCost: yup.string().required('You must enter your sms cost'),
  emailCost: yup.string().required('You must enter your email cost'),
  creditCheckCost: yup.string().required('You must enter your credit check cost'),
  ehfCost: yup.string().required('You must enter your ehf cost'),


  billingPhoneNumber: yup.string().required('You must enter your billing phone number'),
  billingEmail: yup.string().required('You must enter your billing email'),
  billingAddress: yup.string().required('You must enter your billing address'),
  zip: yup.string().required('You must enter your zip'),
  city: yup.string().required('You must enter your city'),
  country: yup.string().required('You must enter your country'),

  bankName: yup.string().required('You must enter your bank name'),
  accountNumber: yup.string()
    .required('You must enter your account number')
    .matches(/^(\S+$)/g, 'This field cannot contain blankspaces'),
  IBAN: yup.string().required('You must enter your IBAN'),
  SWIFTCode: yup.string().required('You must enter your SWIFT code'),


  APTICuserName: yup.string().required('You must enter your APTIC user name'),
  APTICpassword: yup.string().required('You must enter your APTIC password'),
  fpReference: yup.string().required('You must enter your fp reference'),
  name: yup.string().required('You must enter your name'),
  creditLimitCustomer: yup.string().required('You must enter your credit limit for customer'),
  APTIEngineCuserName: yup.string().required('You must enter username'),
  APTIEnginePassword: yup.string().required('You must enter password'),
  fakturaB2B: yup.string().required('You must enter Faktura B2B'),
  fakturaB2C: yup.string().required('You must enter Faktura B2C'),
});

export const validateSchemaCreateClient = yup.object().shape({
  id: yup.string().min(9, "ID should be 9 digit").max(9, "ID should be 9 digit").required("You must enter your organization ID"),
  clientName: yup.string().required("You must enter your Client name"),
  organizationType: yup.string().required("You must select organization type"),
  fullName: yup.string().required("You must enter your name"),
  primaryPhoneNumber: yup.string().required("You must enter your primary phone number"),
  designation: yup.string(),
  email: yup.string().required('You must enter your email').email('Please enter a valid email'),

  contactEndDate: yup.string().required('You must enter your contact end date').typeError("Please Enter valid Date"),
  commision: yup.string().required('You must enter your commision'),
  smsCost: yup.string().required('You must enter your sms cost'),
  emailCost: yup.string().required('You must enter your email cost'),
  creditCheckCost: yup.string().required('You must enter your credit check cost'),
  ehfCost: yup.string().required('You must enter your ehf cost'),

  billingPhoneNumber: yup.string().required('You must enter your billing phone number'),
  billingEmail: yup.string() .email('Must be valid Email') .required('You must enter your billing email'),
  billingAddress: yup.string().required('You must enter your billing address'),
  zip: yup.string().required('You must enter your zip'),
  city: yup.string().required('You must enter your city'),
  country: yup.string().required('You must enter your country'),
  bankName: yup.string().required('You must enter your bank name'),
  accountNumber: yup.string()
    .required('You must enter your account number')
    .matches(/^(\S+$)/g, 'This field cannot contain blankspaces'),
  SWIFTCode: yup.string().required('You must enter your SWIFT code'),
  IBAN: yup.string().required('You must enter your IBAN'),
  
  APTICuserName: yup.string().required('You must enter your APTIC user name'),
  APTICpassword: yup.string().required('You must enter your APTIC password'),
  APTIEnginePassword: yup.string().required('You must enter your APTIC Engine password'),
  fpReference: yup.string().required('You must enter your fp reference'),
  name: yup.string().required('You must enter your name'),
  creditLimitCustomer: yup.string().required('You must enter your credit limit for customer'),
  APTIEngineCuserName: yup.string().required('You must enter username'),
  fakturaB2B: yup.string().required('You must enter Faktura B2B'),
  fakturaB2C: yup.string().required('You must enter Faktura B2C'),
});

export const defaultValue = {
  id: '',
  clientName: '',
  organizationType: '',
  parentClientName: '',
  fullName: '',
  primaryPhoneNumber: '47',
  designation: '',
  email: '',
  password: 'default',

  contactEndDate: null,
  commision: '',
  smsCost: '',
  emailCost: '',
  creditCheckCost: '',
  ehfCost: '',

  contactEndDatep2: new Date(),
  commisionp2: '0',
  smsCostp2: '0',
  emailCostp2: '0',
  creditCheckCostp2: '0',
  ehfCostp2: '0',

  contactEndDatep3: new Date(),
  commisionp3: '0',
  smsCostp3: '0',
  emailCostp3: '0',
  creditCheckCostp3: '0',
  ehfCostp3: '0',

  billingPhoneNumber: '47',
  billingEmail: '',
  billingAddress: '',
  zip: '',
  city: '',
  country: '',
  shippingPhoneNumber: '47',
  shippingEmail: '',
  shippingAddress: '',
  shippingZip: '',
  shippingCity: '',
  shippingCountry: '',
  bankName: '',
  accountNumber: '',
  IBAN: '',
  SWIFTCode: '',


  APTICuserName: '',
  APTICpassword: '',
  name:'',
  fpReference: '',
  creditLimitCustomer: '',
  costLimitforCustomer: '',
  costLimitforOrder: '',
  nvoicewithRegress:'',
  invoicewithoutRegress:'',

  APTIEngineCuserName: '',
  APTIEnginePassword: '',
  vat:[],
  fakturaB2B: '',
  fakturaB2C: '',
  
}

export const defaultValueOnBoard = {
  id: '',
  clientName: '',
  organizationType: '',
  parentClientName: '',
  fullName: '',
  primaryPhoneNumber: '47',
  designation: '',
  email: '',
  password: 'default',

  contactEndDate: null,
  commision: '',
  smsCost: '',
  emailCost: '',
  creditCheckCost: '',
  ehfCost: '',

  contactEndDatep2: new Date(),
  commisionp2: '0',
  smsCostp2: '0',
  emailCostp2: '0',
  creditCheckCostp2: '0',
  ehfCostp2: '0',

  contactEndDatep3: new Date(),
  commisionp3: '0',
  smsCostp3: '0',
  emailCostp3: '0',
  creditCheckCostp3: '0',
  ehfCostp3: '0',

  billingPhoneNumber: '',
  billingEmail: '',
  billingAddress: '',
  zip: '',
  city: '',
  country: '',
  shippingPhoneNumber: '47',
  shippingEmail: '',
  shippingAddress: '',
  shippingZip: '',
  shippingCity: '',
  shippingCountry: '',
  bankName: '',
  accountNumber: '',
  IBAN: '',
  SWIFTCode: '',

  APTICuserName: '',
  APTICpassword: '',
  name:'',
  fpReference: '',
  creditLimitCustomer: '',
  costLimitforCustomer: '',
  costLimitforOrder: '',
  nvoicewithRegress:'',
  invoicewithoutRegress:'',

  APTIEngineCuserName: '',
  APTIEnginePassword: '',
  vat:[],
  fakturaB2B: '',
  fakturaB2C: '',
}

export const defaultValueCreateClient = {
  id: '',
  clientName: '',
  organizationType: '',
  parentClientName: '',
  fullName: '',
  primaryPhoneNumber: '47',
  designation: '',
  email: '',
  password: 'default',

  contactEndDate: null,
  commision: '',
  smsCost: '',
  emailCost: '',
  creditCheckCost: '',
  ehfCost: '',

  contactEndDatep2: new Date(),
  commisionp2: '0',
  smsCostp2: '0',
  emailCostp2: '0',
  creditCheckCostp2: '0',
  ehfCostp2: '0',

  contactEndDatep3: new Date(),
  commisionp3: '0',
  smsCostp3: '0',
  emailCostp3: '0',
  creditCheckCostp3: '0',
  ehfCostp3: '0',

  billingPhoneNumber: '47',
  billingEmail: '',
  billingAddress: '',
  zip: '',
  city: '',
  country: '',
  shippingPhoneNumber: '47',
  shippingEmail: '',
  shippingAddress: '',
  shippingZip: '',
  shippingCity: '',
  shippingCountry: '',
  bankName: '',
  accountNumber: '',
  IBAN: '',
  SWIFTCode: '',

  APTICuserName: '',
  APTICpassword: '',
  name:'',
  fpReference: '',
  creditLimitCustomer: '',
  costLimitforCustomer: '',
  costLimitforOrder: '',
  nvoicewithRegress:'',
  invoicewithoutRegress:'',

  APTIEngineCuserName: '',
  APTIEnginePassword: '',
  vat:[],
  fakturaB2B: '',
  fakturaB2C: '',

}
